### ISSUE TITLE
Error: no utxo

### ISSUE THREAD

**Issue by Abhishekoodles1** [coinables/sweepkey#10]
i am getting the following error when trying to doing a transaction using my private key : 

` no utxo`
`Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.res.setHeader (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/express/lib/response.js:151:12)
    at fn (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/express/lib/response.js:841:10)
    at View.exports.renderFile [as engine] (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/ejs/lib/ejs.js:379:10)
    at View.render (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/express/lib/application.js:561:10)
    at ServerResponse.res.render (/home/abhishek/nodeAppcoldwallet/sweepkey/node_modules/express/lib/response.js:845:7)
    at /home/abhishek/nodeAppcoldwallet/sweepkey/app.js:53:37`

**Comment by coinables** [comment]
Is it a legacy P2PKH address, an address that starts with a "1"?

**Comment by Abhishekoodles1** [comment]
i have created a cold wallet and its public address is 38SXigeP4z7KyPEcjT697vWWkr9LnSsseS . i already checked the deposit and it is working fine, but after I also want to withdraw from my cold wallet using its private key but i am not able to do that. :(

**Comment by coinables** [comment]
Appears to be P2SH segwit. Try using segwitaddress.org save and run locally

**Comment by Abhishekoodles1** [comment]
#coinables thanks a lot now I can withdraw using segwitaddress.org.
