### ISSUE TITLE
are there any examples on how to install it or use it ?

### ISSUE THREAD

**Issue by ghost** [coinables/sweepkey#6]
hi, 
i am new to this whole node.js thing, and would like to know, 
is there any examples on how to install it or use it from command line.,

Thanks

**Comment by rawmaterials** [comment]
i did 
git clone https://github.com/coinables/sweepkey.git

[root@localhost sweepkey]# node app.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)

so i went ahead and did 

npm install express
npm install express
npm install express

**Comment by ghost** [comment]
okie., nginx was causing conflict as it was running on port 80, so i changed port in app.js to 81
but then when i opened my ip on web browser, it tried to redirect me to https version. as my server don't have https , i am stuck.

**Comment by ghost** [comment]
okie., i have managed to make it run
but getting all these , if i enter empty wallet address.


[root@localhost sweepkey]# node app.js
sever running on 80
no utxo
-880
880
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.res.setHeader (/home/deploy/sweepkey/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/home/deploy/sweepkey/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/home/deploy/sweepkey/node_modules/express/lib/response.js:151:12)
    at fn (/home/deploy/sweepkey/node_modules/express/lib/response.js:841:10)
    at tryHandleCache (/home/deploy/sweepkey/node_modules/ejs/lib/ejs.js:208:10)
    at View.exports.renderFile [as engine] (/home/deploy/sweepkey/node_modules/ejs/lib/ejs.js:412:10)
    at View.render (/home/deploy/sweepkey/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/home/deploy/sweepkey/node_modules/express/lib/application.js:561:10)
    at ServerResponse.res.render (/home/deploy/sweepkey/node_modules/express/lib/response.js:845:7)

**Comment by coinables** [comment]
Download files, run npm install to get dependent modules (express, bitcore-lib, request, ejs)
Launch your nodejs app in console  `node app.js` then navigate to your localhost in a browser. 

I did a video series on bitcoin and nodejs that should help.  Sounds like you already have a decent grasp on web dev so you should pick it up quickly.  You can probably start on part 5 https://www.youtube.com/watch?v=Wwv6pK4PBdw

**Comment by ghost** [comment]
okie., for https issue , i put nginx in the middle with cloudflare , so now https is working and on other than port 80.

**Comment by coinables** [comment]
Ooops I forgot I added that. It's just a faux https redirect using inline javascript.  Remove this block from pages index.ejs and address.ejs to stop https redirect. In fact I'm going to change that now. https://github.com/coinables/sweepkey/blob/master/views/pages/index.ejs#L34

**Comment by ghost** [comment]
thanks, really appreciate it.,
